# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: ubuntu-latest
steps:  
- task: UiPathInstallPlatform@3
  inputs:
    cliVersion: 'X_22.10.8418.30339'
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    version: 6.0.x
    includePreviewVersions: true
- task: UiPathPack@3
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'project.json'
    orchestratorConnection: ''
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    runWorkflowAnalysis: false
    traceLevel: 'Warning'
- task: UiPathRunJob@3
  inputs:
    orchestratorConnection: 'UiPath'
    processName: 'TestProcess'
    folderName: 'Deployment'
    user: 'Linux\khoann1999@gmail.com'
    machine: 'Linux'