# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: windows-latest
steps:  
- task: UiPathInstallPlatform@3
  inputs:
    cliVersion: 'WIN_22.10.8418.30339'
- task: UiPathTest@3
  inputs:
    testTarget: TestProject
    orchestratorConnection: 'UiPath'
    parametersFilePath: project.json
    testProjectPath: '$(Build.SourcesDirectory)'
    folderName: 'Deployment'
    traceLevel: 'Warning'
    attachRobotLogs: true
- task: UiPathPack@3
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'project.json'
    orchestratorConnection: ''
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    runWorkflowAnalysis: false
    traceLevel: 'Warning'
- task: UiPathDeploy@3
  inputs:
    orchestratorConnection: 'UiPath'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Deployment'
    traceLevel: 'Warning'

- task: UiPathRunJob@3
  inputs:
    orchestratorConnection: 'UiPath'
    processName: 'TestProcess'
    folderName: 'Deployment'
